FROM ubuntu:16.04
MAINTAINER Joschka Lingemann <joschka.lingemann@cern.ch>

# install packages available through apt-get to reduce build-time
RUN apt-get update && apt-get install -y \
  sudo \
  cmake \
  git \
  python \
  curl \
  libtool \
  build-essential \
  gfortran \
  python-yaml \
  libpcre3 \
  zlib1g \
  libfreetype6 \
  liblzma5 \
  python-libxml2 \
  libxml2 \
  libfftw3-3 \
  libx11-dev \
  libxpm4 \
  libxpm-dev \
  libxft2 \
  libxft-dev \
  libxext6 \
  libxext-dev

# setup work directories
ENV FCCBASE=/usr/local/fcc
ENV SPACK_ROOT=$FCCBASE/spack
RUN mkdir -p $FCCBASE
WORKDIR $FCCBASE

# Set up spack needed for ROOT
RUN git clone https://github.com/llnl/spack -b develop $SPACK_ROOT
RUN git clone https://github.com/jlingema/hep-spack -b fcc $SPACK_ROOT/var/spack/repos/hep-spack

# need this to define apt-get packages, may be useful to split that off the fcc specs
RUN git clone https://github.com/jlingema/fcc-spi -b spack $FCCBASE/fcc-spi
RUN python $FCCBASE/fcc-spi/fcc_define_stack.py --fcc_yaml=$FCCBASE/fcc-spi/docpage/_data/packages.yml -o $SPACK_ROOT/etc/spack/packages.yaml --base_yaml=$FCCBASE/fcc-spi/docker/packages-ubuntu16.04.yaml latest

# compile ROOT
RUN $SPACK_ROOT/bin/spack compiler find && \
    $SPACK_ROOT/bin/spack repo add $SPACK_ROOT/var/spack/repos/hep-spack && \
    $SPACK_ROOT/bin/spack install root

